name: Keploy API Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Change to backend directory
        working-directory: ./backend
        run: echo "Changed to backend"

      - name: Install Dependencies
        working-directory: ./backend
        run: go mod tidy

      - name: Start Application
        working-directory: ./backend
        run: |
          nohup go run main.go &
          sleep 5

      - name: Download Keploy Binary
        working-directory: ./backend
        run: |
          curl -sSfL https://github.com/keploy/keploy/releases/latest/download/keploy-linux-amd64 -o keploy
          chmod +x keploy

      - name: Run Keploy Tests
        working-directory: ./backend
        run: ./keploy test --path=.

      - name: Upload Coverage Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: keploy-test-results
          path: backend/tests
