name: Keploy API Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Install Go dependencies
        working-directory: ./backend
        run: go mod tidy

      - name: Download and Install Keploy CLI
        working-directory: ./backend
        run: |
          curl -sSfL https://github.com/keploy/keploy/releases/latest/download/keploy-linux-amd64 -o keploy
          chmod +x keploy
          sudo mv keploy /usr/local/bin/

      - name: Start Backend App
        working-directory: ./backend
        run: |
          nohup go run main.go > app.log 2>&1 &
          sleep 10
          echo "Backend started, checking if it's running..."
          ps aux | grep "go run main.go" || echo "Backend process not found"

      - name: Wait for application to be ready
        working-directory: ./backend
        run: |
          timeout 30 bash -c 'until curl -f http://localhost:8080/health 2>/dev/null; do sleep 1; done' || echo "Health check failed, continuing anyway"

      - name: Run Keploy Tests
        working-directory: ./backend
        run: |
          if [ -d "./keploy" ]; then
            keploy test --path=.
          else
            echo "No Keploy test data found. Skipping tests."
            exit 0
          fi

      - name: Stop Backend App
        if: always()
        working-directory: ./backend
        run: |
          pkill -f "go run main.go" || echo "No backend process to kill"

      - name: Upload Keploy Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: keploy-test-results
          path: |
            backend/keploy/
            backend/app.log
            backend/test-results/

      - name: Upload Application Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: application-logs
          path: backend/app.log
