name: Keploy API Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Install Dependencies
        run: go mod tidy

      - name: Start Application
        run: |
          nohup go run main.go &
          sleep 5

      - name: Install Keploy
        run: |
          curl --silent -O -L https://keploy.io/ent/install.sh
          chmod +x ./install.sh
          source ./install.sh

      - name: Run Keploy Tests
        run: keploy test --path=.

      - name: Upload Coverage Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: keploy-test-results
          path: backend/tests
